### ISSUE TITLE
Save logits error [TypeError: Can't broadcast]

### ISSUE THREAD

**Issue by xiaoli1996** [RicherMans/CED#17] opened 2024-05-28 05:32 UTC
Thank your release code! I use it on my private dataset, but the error occurs on save_logit.py. My dataset audio length range from 0.1 s-8s. 

File "save_logits.py", line 120, in _save_logits_parallel
    vals[c:c + y.shape[0], :] = y_vals.numpy()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "lib/python3.8/site-packages/h5py/_hl/dataset.py", line 997, in __setitem__
    mspace = h5s.create_simple(selection.expand_shape(mshape))
  File "lib/python3.8/site-packages/h5py/_hl/selections.py", line 264, in expand_shape
    raise TypeError("Can't broadcast %s -> %s" % (source_shape, self.array_shape))  # array shape
TypeError: Can't broadcast (52, 20) -> (18, 20)

**Comment by RicherMans** [comment] 2024-05-28 05:54
Hey,
can you check if it's the last sample? Did the script already save some data?

On a sidenote, my models usually require 160ms as input, so shorter lengths should throw an error (even though not this one)

**Comment by xiaoli1996** [comment] 2024-05-28 06:25
![image](https://github.com/RicherMans/CED/assets/52903099/40d2d87b-8d56-4209-8804-83bf33db27e7)
It seems to have gone wrong at the beginning.

**Comment by RicherMans** [comment] 2024-05-28 09:26
Hey,
hmm if possible can you add some prints in the script to give the values of "c", "vals.shape" and "y_vals.shape"?

I think  the problem is [this line](https://github.com/RicherMans/CED/blob/d13974b9144a7314729dc55a69175c8330ce9614/save_logits.py#L114), which might not be triggered.

As a quick fix, can you change the batch_size by passing `--batch_size 4` to the script?

Kind regards

**Comment by xiaoli1996** [comment] 2024-05-28 13:53
Thank you very much, the logits have been successfully generated!

**Comment by RicherMans** [comment] 2024-05-28 23:45
Err, so either you can close the issue or (I would prefer that), could you maybe identify the problem and provide a pull request? 
Kind regards,
Heinrich

**Closed as completed** 2024-05-29 01:57 UTC
